Repository openmfp/kubernetes-graphql-gateway, pull requests merged in 2025-05, with the labels that each got.

#204 feat: allowing the configuration of the virtual workspace url directly
  cmd/listener.go
  listener/kcp/reconciler_factory.go
  listener/kcp/reconciler_factory_test.go
  listener/kcp/workspace_config.go
  listener/kcp/workspace_config_test.go
Labels: feature

#192 Feat(gateway): sentry
  cmd/gateway.go
  cmd/listener.go
  cmd/root.go
  common/config/config.go
  gateway/manager/manager.go
  gateway/resolver/subscription.go
  gateway/schema/schema.go
  go.mod
  go.sum
  listener/kcp/manager_factory_test.go
  listener/kcp/reconciler_factory.go
  listener/kcp/reconciler_factory_test.go
  tests/gateway_test/suite_test.go
Labels: fix, feature

#220 fix: nil-pointer-dereference
  gateway/resolver/subscription.go
  tests/gateway_test/subscription_test.go
Labels: bug, gateway

#227 docs: auth
  README.md
  cmd/root.go
  common/config/config.go
  docs/authorization.md
  docs/quickstart.md
  gateway/manager/handler.go
  tests/gateway_test/suite_test.go
Labels: documentation, fix
