Repository openmfp/kubernetes-graphql-gateway, pull requests merged in 2025-06, with the labels that each got.

#239 feat: send empty array if no resources in subscription
  gateway/resolver/subscription.go
  tests/gateway_test/subscription_test.go
Labels: fix, feature

#234 fix: prevent overwriting schema in PreReconcile
  listener/kcp/reconciler_factory.go
  listener/kcp/reconciler_factory_test.go
  listener/workspacefile/io_handler.go
Labels: fix, feature

#235 Fix: meaningful errors during subscriptions
  gateway/resolver/resolver.go
  gateway/resolver/subscription.go
  gateway/schema/schema.go
Labels: fix, feature

#247 docs: local test
  docs/contributing.md
  docs/local_test.md
Labels: documentation, fix

#258 feat(tracing): configure otel tracing
  cmd/gateway.go
  go.mod
  go.sum
Labels: feature

#268 Fix: config panic
  cmd/root.go
  common/config/config.go
  gateway/manager/export_test.go
  gateway/manager/handler.go
Labels: fix
